COPY INTO RAW_DB.PUBLIC.raw_sales
FROM @RAW_DB.PUBLIC.my_stage/raw_sales.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW_DB.PUBLIC.csv_format');

COPY INTO RAW_DB.PUBLIC.raw_customers
FROM @RAW_DB.PUBLIC.my_stage/raw_customers.csv
FILE_FORMAT = (FORMAT_NAME = 'RAW_DB.PUBLIC.csv_format');

-- check
-- SELECT * FROM RAW_DB.PUBLIC.raw_sales LIMIT 10;
-- SELECT * FROM RAW_DB.PUBLIC.raw_customers LIMIT 10;
-- SELECT COUNT(*) FROM RAW_DB.PUBLIC.raw_sales;  -- expected ~10,000
-- SELECT COUNT(*) FROM RAW_DB.PUBLIC.raw_customers;  -- expected ~1,000

-- SELECT * FROM RAW_DB.INFORMATION_SCHEMA.LOAD_HISTORY
-- WHERE TABLE_NAME IN ('RAW_SALES', 'RAW_CUSTOMERS')
-- ORDER BY LAST_LOAD_TIME DESC;